ALTER TABLE contacts DROP COLUMN IF EXISTS phone;
ALTER TABLE contacts DROP COLUMN IF EXISTS company;
ALTER TABLE contacts DROP COLUMN IF EXISTS address;
ALTER TABLE contacts DROP COLUMN IF EXISTS birthday;
