FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY services/keyserver/ ./services/keyserver/
COPY go.work ./
WORKDIR /app/services/keyserver
RUN go mod download
RUN CGO_ENABLED=0 go build -o /keyserver .

FROM alpine:3.20
RUN apk --no-cache add ca-certificates
COPY --from=builder /keyserver /keyserver
EXPOSE 8084
CMD ["/keyserver"]
