FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY services/auth/ ./services/auth/
COPY go.work ./
WORKDIR /app/services/auth
RUN go mod download
RUN CGO_ENABLED=0 go build -o /auth .

FROM alpine:3.20
RUN apk --no-cache add ca-certificates
COPY --from=builder /auth /auth
EXPOSE 8081
CMD ["/auth"]
