FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY services/drive/ ./services/drive/
COPY go.work ./
WORKDIR /app/services/drive
RUN go mod download
RUN CGO_ENABLED=0 go build -o /drive .

FROM alpine:3.20
RUN apk --no-cache add ca-certificates
COPY --from=builder /drive /drive
EXPOSE 8083
CMD ["/drive"]
