FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY services/mail/ ./services/mail/
COPY go.work ./
WORKDIR /app/services/mail
RUN go mod download
RUN CGO_ENABLED=0 go build -o /mail .

FROM alpine:3.20
RUN apk --no-cache add ca-certificates
COPY --from=builder /mail /mail
EXPOSE 8082
CMD ["/mail"]
